[package]
name = "external"
version = "0.0.0"
edition.workspace = true
authors.workspace = true

[lib]
name = "external"
path = "./src/lib.rs"

[dependencies]
serde.workspace = true
tokio.workspace = true
general.workspace = true
axum.workspace = true
anyhow.workspace = true
sqlx.workspace = true
dotenvy.workspace = true
config.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
