[package]
name = "general"
version = "0.0.0"
edition.workspace = true
authors.workspace = true


[dependencies]
serde.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
chrono.workspace = true
validator.workspace = true
async-trait.workspace = true
sea-query.workspace = true
sea-query-sqlx.workspace = true
futures.workspace = true
axum.workspace = true
