[workspace]
members = ["packages/central/*"]
resolver = "3"

[workspace.package]
name = "teampro"
authors = ["Kasra Alizadeh"]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
axum = { version = "0.8", features = ["macros", "multipart", "ws"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
general = { path = "packages/central/general" }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.5", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "v7", "serde"] }
axum-extra = { version = "0.10", features = ["full"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-redoc = { version = "6", features = ["axum"] }
hyper = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
socketioxide = "0.17"
async-trait = "0.1"
validator = { version = "0.19", features = ["derive"] }
dotenvy = "0.15"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "uuid",
    "json",
    "chrono",
] }
sea-query = { version = "1.0.0-rc.1", features = [] }
sea-query-sqlx = { version = "0.8.0-rc.9", features = [
    "sqlx-postgres",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
futures = "0.3"
juniper = "0.17.0"
config = "0.15"
